server:
  # 配置端口
   port: 8088
  servlet:
    # 设置项目路径
    context-path: /hbms

# 自定义配置
master:
  name: master-hbms
  version: 0.0.1
  description: 滑冰场管理系统

spring:
  profiles:
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 配置mybatis参数
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  # 指定 mapper 文件的位置
  mapper-locations: mybatis/mapper/*Mapper.xml
  # POJO 扫描包来让 MyBatis 自动扫描到自定义 POJO
  type-aliases-package: com.master.hbms.**.domain